name: Test-build image

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Test image build
        run: docker build . --file Dockerfile
